version: '3.7'
services:
  db:
    image: mariadb
    container_name: u-docs-database
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: demodemo
      MYSQL_DATABASE: u-docs
    networks:
      - u-docs-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - u-docs-net

  app:
    container_name: u-docs-server
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    depends_on: 
      - db
    networks:
      - u-docs-net

volumes: 
  db-data:

networks: 
  u-docs-net: